### ISSUE TITLE
[Bug] Al salir de un combate random teletransporta al jugador a un bosque

### ISSUE THREAD

**Issue by Dokman** [AsparagusEduardo/pokeemerald#1]
De manera random al salir de un combate teletransporta al personaje a una zona fuera del mapa, por tanto no guarda la posición del personaje y la carga mal y crea un bug donde terminas en las colisiones del mapa.

**Comment by AsparagusEduardo** [comment]
¿Cuál fué el último lugar donde ocurrió? Probé más de 50 peleas en la Ruta 101 y no lo he podido reproducir. (A pesar de que la última vez que me pasó pude hacerlo ahí).

Si se puede, ¿tienes algún .sav antes de que pasara?

**Comment by Dokman** [comment]
He estado retesteando y me pasaba en el bosque pasado la ruta 101, pero ahora no me sucede. Es muy raro. Voy a testear creando una partida nueva, mañana mando un reporte.

**Comment by AsparagusEduardo** [comment]
Ok, voy a probar en el Bosque a ver si lo puedo reproducir.
¿La partida que tenías la habías hecho antes del último commit?

**Comment by Dokman** [comment]
Justo he recompilado para empezar limpio, incluso he reclonado, pero se ha reproducido y estoy pensando que será culpa del compilado, ya que cuando he compilado con mi maquina con arch-linux no ha habido ningún bug y en cambio ahora en windows me da el error.

**Comment by AsparagusEduardo** [comment]
> Justo he recompilado para empezar limpio, incluso he reclonado, pero se ha reproducido y estoy pensando que será culpa del compilado, ya que cuando he compilado con mi maquina con arch-linux no ha habido ningún bug y en cambio ahora en windows me da el error.

También en el Bosque o la Ruta 101?

**Comment by Dokman** [comment]
Ruta 101 y en bosque, en general pasa con los entrenadores, cuando terminas un combate con ellos, he reproducido el bug así dos veces.

**Comment by AsparagusEduardo** [comment]
Si, me acaba de pasar. Lo voy a revisar.

**Comment by AsparagusEduardo** [comment]
Me di cuenta que cometí el mismo que la última vez que tuve este error xD
Ahora en este último commit debería estar solucionado.
¡Gracias por avisar!
