### ISSUE TITLE
Como activar un grupo de dia/noche en porymap?

### ISSUE THREAD

**Issue by Dokman** [AsparagusEduardo/pokeemerald#2]
Se pueden scriptear desde porymap ya que es mas sencillo o hay que programarlo?
No entiendo muy bien el C pero al final al ser un derivado del C++ puedo mirarme algo de código y ver si puedo solventar algo.
Pero no entiendo muy bien como va, ya que soy muy noob en el hackeo de roms.

**Comment by AsparagusEduardo** [comment]
¿Dices en este repo?
Click derecho en el grupo que quieres activar:
![image](https://user-images.githubusercontent.com/2904965/97047331-2ad2f480-154f-11eb-9793-a03de713f0a3.png)

Y C++ se derivó de C, no al revés ajajajaja
