### ISSUE TITLE
[Bug] Spanish items

### ISSUE THREAD

**Issue by Dokman** [AsparagusEduardo/pokeemerald#8]
Can't compile in some line that i don't know, that have a bug
![image](https://user-images.githubusercontent.com/2290904/97782102-e919fd80-1b8f-11eb-9cf3-34c868d153e0.png)

**Comment by Dokman** [comment]
[ITEM_ODD_KEYSTONE] =
    {
        .name = _("Odd Keystone"),
        .itemId = ITEM_ODD_KEYSTONE,
        .price = 2100,
        .description = sOddKeystoneDesc,
        .pocket = POCKET_ITEMS,
        .type = 4,
        .fieldUseFunc = ItemUseOutOfBattle_CannotUse,
        .secondaryId = 0,
    },


src/data/items.h:7398: `sOddKeystoneDesc' undeclared here (not in a function)

**Comment by AsparagusEduardo** [comment]
Somehow I didn't get the notification. I'll fix it tonight when I get home

**Comment by AsparagusEduardo** [comment]
Sorry for the delay. It should now be fine!
